### ISSUE TITLE
How to set up coins that will be checked in each desired quote currency (BTC, ETH, USDT, BNB,...) ?

### ISSUE THREAD

**Issue by bluetyphoon77** [w1ld3r/crypto-signal#12]
Is it possible to set it ?
For example if I want to check all those coins : X, Y, Z ,.... in all defined quotes for example : BNB, ETH, USDT ?
In order not to have to write them all ?

thanks

**Comment by w1ld3r** [comment]
Hello @bluetyphoon77, You can by defining them in `all_pairs` section in your config file.
