### ISSUE TITLE
conditionals - not working

### ISSUE THREAD

**Issue by danield32** [w1ld3r/crypto-signal#15]
It seems that "conditionals" rules are not working - or are not sending notifications - or I didn't understand how they are working.
If I run a docker image with a config.yml - I'm receiving notification for same coin - same indicators, but if I add those indicators in a "rule" in "conditionals" section, I'm not receiving anything:

STR:
defaults.yml(original project file, except that I've set everything to enabled; false)
config.yml - a have something like this:
`
indicators:
....
  iiv:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - iiv
      hot: 1
      cold: 0
      candle_period: 1h
      indicator_label: "IIV - STRATEGY"
      
  ichimoku:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - leading_span_a
        - leading_span_b
      hot: true
      cold: true
      candle_period: 1h
      indicator_label: 'Ichimoku'
      mute_cold: true
      
  ma_ribbon:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - pval
        - corr
      hot: 10
      cold: -10
      hot_label: 'Uptrend is coming'
      cold_label: 'Downtred is coming'
      candle_period: 1h
      pval_th: 20
      ma_series: 5, 15, 25, 35, 45
      mute_cold: true

informants:
  ohlcv:
    - enabled: true
      signal:
        - high
        - low
        - close
      candle_period: 1h
      period_count: 14

conditionals:

############### ichimoku & ma_ribbon #################
  - label: "1h - ichimoku && ma_ribbon"
    hot:
      - ichimoku: 0
      - ma_ribbon: 0

############### ichimoku & iiv #################
  - label: "1h - ichimoku && iiv"
    hot:
      - ichimoku: 0
      - iiv: 0

############### ma_ribbon #################
  - label: "1h - ma_ribbon && iiv"
    hot:
      - ma_ribbon: 0
      - iiv: 0
`
If i run:
 docker run --rm -i -v D:\DEV\test_notifications\crypto-signal\app:/app dev/crypto-signals:latest 

- I'm not receiving anything in telegram, but if I run same config.yml without rules in "conditionals" section, I'm receiving alerts(same time) for the same indicators used in rules, like;
binance-WAVES/USDT-ichimoku-Ichimoku is hot!
[1h] Prices: [ High: 12.6772 Low: 12.6282 Close: 12.6772]
binance-WAVES/USDT-ma_ribbon- is hot!
[1h] Prices: [ High: 12.6772 Low: 12.6282 Close: 12.6772]
// => if I've understand how conditions work, this should have triggered first condition
![NoCondition](https://user-images.githubusercontent.com/47819737/108575026-9e301b80-7321-11eb-8652-d543c839b3b9.png)

Running with docker on windows:
docker build -t dev/crypto-signals:latest .
docker run --rm -i -v D:\DEV\test_notifications\crypto-signal\app:/app dev/crypto-signals:latest

docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

I really appreciate if you can point me in the right direction!
Thank you!

------
@w1ld3r - sorry for bad bug posting  - attached the defaults.yml and config.yml into a zip file(cannot upload ymls)
[configAndDefaultsYmls.zip](https://github.com/w1ld3r/crypto-signal/files/6022337/configAndDefaultsYmls.zip)
And yes - as MartijnvDijk said - if i remove analysis.config.candle_period i now receive the notifications - but without Price
![image](https://user-images.githubusercontent.com/47819737/108716871-4e21a680-7525-11eb-8e56-b51edb5f22cd.png)

Thank you guys!

**Comment by MartijnvDijk** [comment]
@danield32 it seems you are using the Telegram notifier. In this case, removing "analysis" from template (in config.yml) fixed the problem (for now). (E.g.  removing: analysis.config.candle_period)

**Comment by w1ld3r** [comment]
@danield32 can you use the template "Bug report" ? I can't reproduce your issue with the partial `config.yml` you've provided.
