### ISSUE TITLE
support request :)

### ISSUE THREAD

**Issue by dracmic** [w1ld3r/crypto-signal#18]
Hello w1ld3r,
 Maybe you are busy but can you help me to setup the bot for volume growth detection?

Best regards

**Comment by w1ld3r** [comment]
Hello @dracmic,
I don't think crypto-signal have this functionnaly.
Haven't you find an existing project allowing this ?

**Comment by dracmic** [comment]
Your fork has iiv and from my understanding is the same

**Comment by w1ld3r** [comment]
This project is really not made for this and the project is spagetti code.
I want to have this signal but, I prefer developping it from scratch instead of adding the functionnaly to crypto-signal.

**Comment by dracmic** [comment]
@w1ld3r I suppose that you have something done ... can you look for me on discord/skype on same nickname  to discuss more?

**Comment by w1ld3r** [comment]
Nothing done yet, just thinking of how to make it the best way. Ping me on Discord `w1ld3r#9379`.
