### ISSUE TITLE
[BUG] /usr/local/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame

### ISSUE THREAD

**Issue by onradr** [w1ld3r/crypto-signal#21]
Hi @w1ld3r 
If I run with the app with "ma_crossover", I am getting the following message on output.
I don't know if it will cause a calculation or comparison error, but I wanted to let you know.

```
ERROR:
Starting Worker-209
Starting default analyzer...
Using the following exchange(s): ['binance']
Getting data for ['TLM/USDT']
/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame
```

**Comment by idmahbub** [comment]
**i have some issue, this my config.yml :**

`
settings:
  log_level: INFO
  update_interval: 120
  start_worker_interval: 2
  market_data_chunk_size: 1
  timezone: Europe/Paris
exchanges:
  binance:
    required:
      enabled: true
    all_pairs:
      - USDT
indicators:
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 1h
      period_count: 14
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - rsi
      hot: 40
      cold: 60
      candle_period: 1d
      period_count: 14
  bollinger:
    - enabled: true
      candle_period: 1h
      alert_enabled: true
      alert_frequency: always
      period_count: 25
      std_dev: 2.5
      signal:
        - low_band
        - close
        - up_band
      mute_cold: false
    - enabled: true
      candle_period: 1d
      alert_enabled: true
      alert_frequency: always
      period_count: 25
      std_dev: 2.5
      signal:
        - low_band
        - close
        - up_band
      mute_cold: false
  aroon_oscillator:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      sma_vol_period: 50
      period_count: 14
      signal:
        - aroon
      candle_period: 1h
conditionals:
  - label: "Signal to buy"
    hot:
      - rsi: 0
      - rsi: 1
    cold:
      - bollinger: 0
  - label: "Signal to buy"
    hot:
      - rsi: 1
  - label: "Signal to sell"
    cold:
      - rsi: 1
      - rsi: 0
    hot:
      - aroon_oscillator: 0
notifiers:
    telegram:
        required:
            token: sss
            chat_id: aaaa
        optional:
            parse_mode: html
            template: "[{{market}}] {{indicator}} {{status}} {{values}} {{ '\n' -}}"
`


**No notifications come for me, in my warning log :**
`No configured markets, using all available on exchange.
Getting all ['USDT'] market pairs for binance 
enabled notifers: ['telegram']
Starting Worker-1
Starting default analyzer...
Using the following exchange(s): ['binance']
Getting data for ['BTC/USDT']
enabled notifers: ['telegram']
Starting Worker-2
Starting default analyzer...
Using the following exchange(s): ['binance']
Getting data for ['ETH/USDT']
Beginning analysis of binance
Beginning analysis of BTC/USDT
enabled notifers: ['telegram']
Starting Worker-3
Starting default analyzer...
Using the following exchange(s): ['binance']
Getting data for ['BNB/USDT']
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)`

**Comment by w1ld3r** [comment]
> Hi @w1ld3r
> If I run with the app with "ma_crossover", I am getting the following message on output.
> I don't know if it will cause a calculation or comparison error, but I wanted to let you know.
> 
> ```
> ERROR:
> Starting Worker-209
> Starting default analyzer...
> Using the following exchange(s): ['binance']
> Getting data for ['TLM/USDT']
> /usr/local/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
>   self._setitem_single_block(indexer, value, name)
> /usr/local/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame
> ```

Have you check if the value are good ? I've already notice this warning but, for what I remenber, it was not a big issue.

**Comment by w1ld3r** [comment]
> **i have some issue, this my config.yml :**
> 
> `
> settings:
> log_level: INFO
> update_interval: 120
> start_worker_interval: 2
> market_data_chunk_size: 1
> timezone: Europe/Paris
> exchanges:
> binance:
> required:
> enabled: true
> all_pairs:
> - USDT
> indicators:
> rsi:
> - enabled: true
> alert_enabled: true
> alert_frequency: always
> signal:
> - rsi
> hot: 30
> cold: 70
> candle_period: 1h
> period_count: 14
> - enabled: true
> alert_enabled: true
> alert_frequency: always
> signal:
> - rsi
> hot: 40
> cold: 60
> candle_period: 1d
> period_count: 14
> bollinger:
> - enabled: true
> candle_period: 1h
> alert_enabled: true
> alert_frequency: always
> period_count: 25
> std_dev: 2.5
> signal:
> - low_band
> - close
> - up_band
> mute_cold: false
> - enabled: true
> candle_period: 1d
> alert_enabled: true
> alert_frequency: always
> period_count: 25
> std_dev: 2.5
> signal:
> - low_band
> - close
> - up_band
> mute_cold: false
> aroon_oscillator:
> - enabled: true
> alert_enabled: true
> alert_frequency: always
> sma_vol_period: 50
> period_count: 14
> signal:
> - aroon
> candle_period: 1h
> conditionals:
> 
>     * label: "Signal to buy"
>       hot:
>       
>       * rsi: 0
>       * rsi: 1
>         cold:
>       * bollinger: 0
> 
>     * label: "Signal to buy"
>       hot:
>       
>       * rsi: 1
> 
>     * label: "Signal to sell"
>       cold:
>       
>       * rsi: 1
>       * rsi: 0
>         hot:
>       * aroon_oscillator: 0
>         notifiers:
>         telegram:
>         required:
>         token: sss
>         chat_id: aaaa
>         optional:
>         parse_mode: html
>         template: "[{{market}}] {{indicator}} {{status}} {{values}} {{ '\n' -}}"
>         `
> 
> 
> **No notifications come for me, in my warning log :**
> `No configured markets, using all available on exchange.
> Getting all ['USDT'] market pairs for binance
> enabled notifers: ['telegram']
> Starting Worker-1
> Starting default analyzer...
> Using the following exchange(s): ['binance']
> Getting data for ['BTC/USDT']
> enabled notifers: ['telegram']
> Starting Worker-2
> Starting default analyzer...
> Using the following exchange(s): ['binance']
> Getting data for ['ETH/USDT']
> Beginning analysis of binance
> Beginning analysis of BTC/USDT
> enabled notifers: ['telegram']
> Starting Worker-3
> Starting default analyzer...
> Using the following exchange(s): ['binance']
> Getting data for ['BNB/USDT']
> /usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
> iloc._setitem_with_indexer(indexer, value)`

Please create a new issue using the `BUG` template.

**Comment by onradr** [comment]
> > Hi @w1ld3r
> > If I run with the app with "ma_crossover", I am getting the following message on output.
> > I don't know if it will cause a calculation or comparison error, but I wanted to let you know.
> > ```
> > ERROR:
> > Starting Worker-209
> > Starting default analyzer...
> > Using the following exchange(s): ['binance']
> > Getting data for ['TLM/USDT']
> > /usr/local/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
> > A value is trying to be set on a copy of a slice from a DataFrame
> > 
> > See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
> >   self._setitem_single_block(indexer, value, name)
> > /usr/local/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
> > A value is trying to be set on a copy of a slice from a DataFrame
> > ```
> 
> Have you check if the value are good ? I've already notice this warning but, for what I remenber, it was not a big issue.

**Comment by onradr** [comment]
thanks @w1ld3r
