### ISSUE TITLE
[FEATURE] Config.YML

### ISSUE THREAD

**Issue by onradr** [w1ld3r/crypto-signal#22]
hi @w1ld3r 
I've been looking for the setting that will produce the best signal for a long time, but I haven't found it yet. If you have a setting that I can base on and that can generate a useful signal, is it possible to share your config.yml?

**Comment by w1ld3r** [comment]
Hello @onradr, you can take a look [here](https://admiralmarkets.com/education/articles/forex-strategy) for strategies.
I can't share my config file. Try to ask on the [Crypto-Signal](https://discord.gg/aYzbDKcz) discord.
