### ISSUE TITLE
./config.guess: unable to guess system type

### ISSUE THREAD

**Issue by tsumey** [w1ld3r/crypto-signal#30]
**Describe the bug**
config.guess is too old : 2006-07-02 to recognize my operating system

**To Reproduce**
2. docker build -t dev/crypto-signals:latest .

**Desktop**
 - OS name and version : Linux RPI4 5.10.44-v8+ #1429 SMP PREEMPT Fri Jun 25 10:03:37 BST 2021 aarch64 GNU/Linux
 - crypto-signal branch : w1ld3r
 - Docker version 20.10.7, build f0df350
![2021-06-26 04_25_14-pi@RPI4_ ~](https://user-images.githubusercontent.com/22683670/123499376-91f0fd80-d636-11eb-9b94-c5b6715a2402.png)

**Comment by w1ld3r** [comment]
Can you send me the link, to download the iso, your are using for your Raspberry Pi 4 ?
But, I highly suggest you to use [Ubuntu Server](https://ubuntu.com/download/raspberry-pi) on your Raspberry Pi 4.

**Comment by tsumey** [comment]
Sure, I currently use this one : 

https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/

I will try your advice.

**Comment by w1ld3r** [comment]
U'll have newer packages, so maybe it'll resolve ur issue.

**Comment by tsumey** [comment]
I still get the same issue :
![2021-06-27 02_27_31-root@ubuntu_ _home_ubuntu_crypto-signal](https://user-images.githubusercontent.com/22683670/123529327-5bc38480-d6ef-11eb-95f8-096a4e792cfa.png)

Maybe the build doesn't like 64 bits and I should go back to 32 bits.

**Comment by w1ld3r** [comment]
What's your Python version ?

**Comment by w1ld3r** [comment]
Can you give the return of this command: `sudo find / -name "config.guess"`? Because, maybe you'll have to update the `config.guess` file located in a docker directory.

**Comment by tsumey** [comment]
You'll find below the return :

**root@ubuntu:/home/ubuntu/crypto-signal# sudo find / -name "config.guess"
/var/lib/docker/overlay2/01a85929d47e93a4e6a6637ae71132c89289777e0853a64fcf5735be0d1bd26a/diff/tmp/ta-lib/config.guess
/var/lib/docker/overlay2/2cfc06ff67704b1e942a77ce7841fee185cb1f1ac54438fc6f300ca4c7960fb2/diff/tmp/ta-lib/config.guess
/var/lib/docker/overlay2/73c6f5cd6b9d0bdb633bde4879a0a263998fce579bdd6cb4155a3f8160e003e6/diff/tmp/ta-lib/config.guess
/var/lib/docker/overlay2/42545e9456b0896d174a223a6068520892d18361fb8c48f2caaf1461a47a4305/diff/usr/share/libtool/build-aux/config.guess
/var/lib/docker/overlay2/42545e9456b0896d174a223a6068520892d18361fb8c48f2caaf1461a47a4305/diff/usr/share/automake-1.16/config.guess
/var/lib/docker/overlay2/42545e9456b0896d174a223a6068520892d18361fb8c48f2caaf1461a47a4305/diff/usr/share/misc/config.guess
/var/lib/docker/overlay2/b018e91952da1ab3c4e953e0cd4b3808479b66d91f4df5400ee05a3a133d96a5/diff/tmp/ta-lib/config.guess
**

I tried to update all config.guess I found with this command, and my guess is that I didn't update the right config.guess

![image](https://user-images.githubusercontent.com/22683670/124198645-6015e600-dad1-11eb-8ef2-02785928458e.png)

Last savannah file is : 

![image](https://user-images.githubusercontent.com/22683670/124198679-70c65c00-dad1-11eb-8416-b049ca142bb9.png)

Do you know where should I put the updated file ?

Thanks for your help.

**Comment by w1ld3r** [comment]
The error seems to come from the ta-lib configuration. So maybe updating all ta-lib config.guess files will resolve your issue.

**Comment by w1ld3r** [comment]
Also, you can take a look at this issue from the ta-lib github repo: https://github.com/mrjbq7/ta-lib/issues/222
