### ISSUE TITLE
[BUG] SyntaxError when trying to run docker

### ISSUE THREAD

**Issue by rd-mg** [w1ld3r/crypto-signal#35]
SyntaxError when trying to run docker after update branch to latest commit [72827f7](https://github.com/w1ld3r/crypto-signal/commit/72827f79050924ca185a3b79af92736fb83d23b7)

**To Reproduce**
1. git clone '...'
2. docker build -t dev/crypto-signals:latest .
3. docker run '....'
4. Error
root@iZrj9auk43zyouqwlzay67Z:~/crypto-signal# docker run --rm -ti -v $PWD/app:/app dev/crypto-signals:latest
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from behaviour import Behaviour
  File "/app/behaviour.py", line 17, in <module>
    from analysis import StrategyAnalyzer
  File "/app/analysis.py", line 12, in <module>
    from analyzers.indicators import *
  File "/app/analyzers/indicators/ichimoku.py", line 136
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax
root@iZrj9auk43zyouqwlzay67Z:~/crypto-signal# 

**Expected behavior**
Run docker container

**Machine**
 - OS Debian 10.9
 - crypto-signal develop
 - Docker version 20.10.7, build f0df350

**Additional context**
Docker imagen built without errors

**Comment by w1ld3r** [comment]
Sorry about that, it's m'y mistake. Should be fine now.

**Comment by rd-mg** [comment]
It works!

Thank you

$ docker run --rm -ti -v $PWD/app:/app dev/crypto-signals:latest
No configured markets, using all available on exchange.
All workers are running!
