### ISSUE TITLE
[FEATURE] ... Scalping 5m

### ISSUE THREAD

**Issue by mercadeoweb** [w1ld3r/crypto-signal#36]
Hello sir,

Excellent work.. congratulations!

Please, can you share a config for scalping 5 minutes?

This is my actual config but is for intraday and maybe it has a lot of unnecessary options.

https://pastebin.com/4pB5vuXG

Thanks in advanced

**Comment by w1ld3r** [comment]
Thanks for your gratitude ! I'm sorry but, I don't have this type of configuration. You can ask on the Discord.
