### ISSUE TITLE
[BUG]docker: Error response from demon

### ISSUE THREAD

**Issue by rajaapr1692** [w1ld3r/crypto-signal#42]
docker: Error response from demon when trying to run docker 
To Reproduce

git clone '...'
docker build -t dev/crypto-signals:latest .
docker run '....'
Error
C:\Users\vetri\crypto-signal>docker run --rm -ti -v $PWD/app:/app dev/crypto-signals:latest
docker: Error response from daemon: create $PWD/app: "$PWD/app" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
Expected behavior
Run docker container

Machine

OS Name:Microsoft Windows 10 Pro
OS Version:10.0.19042 N/A Build 19042
crypto-signal develop
Docker version 20.10.7, build f0df350

Additional context
Docker imagen built without errors

**Comment by w1ld3r** [comment]
Try to replace `$PWD` by the full path. `$PWD` return a bad character that Docker can't handle. The issue don't come from `crypto-signal`.
