### ISSUE TITLE
Label not printed

### ISSUE THREAD

**Issue by exrienz** [w1ld3r/crypto-signal#44]
Hi, 

Im trying to print the label as shown on this yaml code.
![image](https://user-images.githubusercontent.com/14239668/131099012-a17b8127-aa57-4fe2-8b62-105038a98c8f.png)

But this is the output. It just not able to discover the label. Is this a bug or Im missing a step?
![image](https://user-images.githubusercontent.com/14239668/131098872-0569976f-b70b-4d9c-870b-8707d24f8706.png)

**Comment by w1ld3r** [comment]
Are you using conditional notification ?
