### ISSUE TITLE
first_run is not working ![BUG]

### ISSUE THREAD

**Issue by n4v3d** [w1ld3r/crypto-signal#46]
**Describe the bug**
i set first_run to true in config.yml
i want to skip first alert because its false .

**config.yml**
settings:
  update_interval: 300
  first_run: true
  market_pairs:
    - ETH/BTC
    - LTC/BTC
    - XMR/BTC

exchanges:
    binance:
        required:
            enabled: true
indicators:
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 5m
          period_count: 14
          hot_label: 'Buy Alert'
          cold_label: 'Sell Alert'
          indicator_label: 'RSI 1d 30/70'
          mute_cold: false
notifiers:
    webhook:
      required:
        url: https://webhook.site/68bcdd35-831a-49c8-b0ff-0b9cf5922270
      optional:
        username: null
        password: null

**Comment by w1ld3r** [comment]
Will need logs to debug your issue.
