### ISSUE TITLE
Wrong values for the STOCHRSI

### ISSUE THREAD

**Issue by bluetyphoon77** [w1ld3r/crypto-signal#5]
I've set up the 3 infos. They are totally inaccurate when I compare to Tradingview. 
Why using it then ? Is there a way to get the righ values ? To set up the config like in Tradingview (the 4 settings)

Thanks

**Comment by bluetyphoon77** [comment]
Is it maybe because I have to set
"market_data_chunk_size: 1"
?
Do you get the accurate results yourself ? I just need the K. But it is totally wrong most of the time....

**Comment by w1ld3r** [comment]
Please, re-create the issue using the BUG template.
