### ISSUE TITLE
setup help

### ISSUE THREAD

**Issue by Cleversss1** [w1ld3r/crypto-signal#52]
hi. I can't install. Where can I download the config.yml file ready? Can you upload the setup with pictures?

**Comment by Cleversss1** [comment]
where is the git clone https://github.com/w1ld3r/crypto-signal.git?? C/D?? help

**Comment by Badn1nja** [comment]
Check the readme it's on there

**Comment by Badn1nja** [comment]
Be sure you have git installed in your system.

    Clone this repo git clone https://github.com/w1ld3r/crypto-signal.git

    Enter to cripto-signal folder cd crypto-signal

    Switch to develop branch git checkout develop

    Create a config.yml file and put it into "app" folder.

    Build your own Docker image, for example, docker build -t dev/crypto-signals:latest .

    For testing and debugging run docker with "-t" option docker run --rm -ti -v $PWD/app:/app dev/crypto-signals:latest

    For production run in daemon mode using "-d" option docker run --rm -di -v $PWD/app:/app dev/crypto-signals:latest

**Comment by Cleversss1** [comment]
hi badninja. I have one last request. How can I make config.yml file? do you have it? I can not do this. I did not understand. I am sorry.

**Comment by Badn1nja** [comment]
No worries mate. I will upload mine - It's "complete" just disabled all the ones I was not using

**Comment by Badn1nja** [comment]
https://pastebin.com/cyRUiKWr

**Comment by Cleversss1** [comment]
You are a very kingly man. thank you. I can add other coins to this config
file, right? with the same usdt parity after sushi?

Badn1nja ***@***.***>, 31 Ara 2021 Cum, 15:43 tarihinde şunu
yazdı:

**Comment by Badn1nja** [comment]
Yeah you can.. or do all pairs but this is quite spammy for low cap coins

**Comment by Cleversss1** [comment]
thank you very much.  for everything

31 Ara 2021 Cum, saat 19:43 tarihinde Badn1nja ***@***.***>
şunu yazdı:
