### ISSUE TITLE
[FEATURE] ... I want to make it help me T T

### ISSUE THREAD

**Issue by hellomyvision** [w1ld3r/crypto-signal#55]
Hello gentle guys?

I'm studying tradingview pine script source code.

I want to make some indicator like my picture below.

I'd like to mark when the close and leadline are cross eachother over or under only.

but I don't know why the gogo and nono mark are discoverd at all time.

pleae help me  gentle guys!

//@version=5
indicator("my Script", overlay=true)
laggingSpan2Periods = input.int(26, minval=1, title="Leading Span B Length")
donchian(len) => math.avg(ta.lowest(len), ta.highest(len))
leadline = donchian(laggingSpan2Periods)
displacement = input.int(26, minval=1, title="Displacement")

plot(close)
p2 = plot(leadline, offset = displacement - 1, color=color.red,
	 title="Leading Span B")

isOver = ta.crossover(close, leadline)
isUnder = ta.crossunder(close, leadline)

plotshape(isOver, text="gogo~", style=shape.arrowup, location=location.belowbar, size=size.large, color=color.green)
plotshape(isUnder, text="nono~", style=shape.arrowdown, location=location.abovebar, size=size.large, color=color.red)

![20220222_161559](https://user-images.githubusercontent.com/100189261/155081560-6c675c83-4372-40d4-9f1e-dadb9c76844a.png)
![20220222_161630](https://user-images.githubusercontent.com/100189261/155081567-180ea1c5-5d0d-4cd9-bd71-221be74428e5.png)
f

**Comment by w1ld3r** [comment]
Hello @hellomyvision, have you asked on the discord ?
Here is the link: https://discord.gg/MWTJVFf
