### ISSUE TITLE
[FEATURE] Added new indicator in the main branch (SQZMOM)

### ISSUE THREAD

**Issue by velajos** [w1ld3r/crypto-signal#59]
Greetings friend, 

A new indicator has been added in the main branch called SQZMOM and I wanted to know if you can add it to your code so that it can work with conditionals. Thanks in advance @w1ld3r 

https://github.com/CryptoSignal/Crypto-Signal/commit/11cf9096c89d26846011f5a77c7389c6b3b581b6

**Comment by w1ld3r** [comment]
Hello @Juanjacinto123, sorry for the delay. Here it is #60 !

**Comment by velajos** [comment]
> Hello @Juanjacinto123, sorry for the delay. Here it is #60 !

Thanks!
