### ISSUE TITLE
Conditionals notifiers no charts attached

### ISSUE THREAD

**Issue by braverynew** [w1ld3r/crypto-signal#61]
When I use conditional and enable chart in config.yml. But It sent notification without chart. How can I config it?
My config:
settings:
  log_level: INFO
  update_interval: 300
  start_worker_interval: 2
  market_data_chunk_size: 1
  enable_charts: true
indicators:
  candle_recognition:
    - enabled: true
      alert_enabled: true
      alert_frequency: always
      signal:
        - doji
      candle_check: 1
      notification: hot
      candle_period: 1d
      hot: 0
      cold: 0
      chart: true
If i run without conditional. It send chart

Thanks

**Comment by w1ld3r** [comment]
Hello @braverynew, chart hasn't been implemented in conditional mode.

**Comment by braverynew** [comment]
Thanks. conditional module working like a charm! waiting for update chart included.

**Comment by w1ld3r** [comment]
Thanks for your feedback !
