### ISSUE TITLE
WHEN setting multiple EXCHANGES, the script just gives results for the FIRST ONE in the list

### ISSUE THREAD

**Issue by bluetyphoon77** [w1ld3r/crypto-signal#9]

**Comment by w1ld3r** [comment]
Hello @bluetyphoon77, please use the issue template.

**Comment by bluetyphoon77** [comment]
Will do when I have time. Because seems previous help I brought is not used to fix anything. Cheers

**Comment by bluetyphoon77** [comment]
This is working now ! ;)

**Comment by w1ld3r** [comment]
Nice !
